# Trabalho 1 - PDI
### Ingrid Dayane da Silva Ferreira (20200154050)

Desenvolva, em uma linguagem de programação de sua escolha, um sistema para abrir, 
exibir, manipular e salvar imagens RGB com 24 bits/pixel (8 bits/componente/pixel). Não 
use bibliotecas ou funções especiais de processamento de imagens. O sistema deve ter a 
seguinte funcionalidade:

1. Correlação m x n com offset, sobre R, G e B. O offset e o filtro (dimensões e valores 
da máscara) devem ser definidos em um arquivo (txt) à parte. Realize testes com os 
filtros Gaussiano 5x5, Sobel horizontal e Sobel vertical, e explique os resultados.
Utilize extensão por zeros. Para visualização do Sobel, aplique valor absoluto seguido 
por expansão de histograma para [0, 255].

In [77]:
def filter(i, f, nome_resultado):
    # importando as bibliotecas necessárias ao processamento
    import cv2
    import numpy as np
    import matplotlib.pyplot as plt

            # leitura do txt com as informações do filtro
    with open(f, 'r') as f:  # abrindo o txt do filtro
        m = int(f.readline()) # linhas
        n = int(f.readline()) # colunas
        offset = int(f.readline())
        filtro = [[0] * n for _ in range(m)] # criando uma matriz para colocar o filtro
        linhas = f.readlines()

        for j, line in enumerate(linhas): # colocando o filtro na matriz criada
            f1 = (line.split())
            filtro[j] = f1

        for e in range(m): # transformando cada posição do filtro em ponto flutuante
            for r in range(n):
                filtro[e][r] = float(filtro[e][r])

    img = cv2.imread(i) # lendo a imagem
    img_m, img_n, _ = img.shape # terceira dimensão = bandas (R,G,B)

    img_resultante = np.zeros_like(img) # gerando uma imagem resultante de mesmo tamanho da imagem de entrada

    '''
    A partir daqui já temos todas as informações necessárias para aplicarmos o filtro à imagem:
        - m
        - n
        - offset
        - filtro
        - imagem
        - altura da imagem (qtd de linhas)
        - largura da imagem (qtd de colunas)
        - imagem resultante (preenchida com zeros e pronta para receber os cálculos da aplicação do filtro)
            A imagem resultante tem o mesmo tamanho da imagem de entrada, pois utilizaremos extensão por zero
    '''
    # Separando os canais e expandindo o histograma
    R = img[:,:,0]
    G = img[:,:,1]
    B = img[:,:,2]
    
    for b in [R, G, B]: # Aplicando o filtro em cada canal
        maximo = np.max(b)
        minimo = np.min(b)
        padded_b = np.pad(b, ((m//2, m//2), (n//2, n//2)), mode='constant') # corrigindo o problema das dimensões
        for q in range(img_m): # aplicar o filtro em cada posição da imagem
            for w in range(img_n):
                vizinhanca = padded_b[q:q+m, w:w+n] # recortando a vizinhança para realizar a convolução do filtro (considerando a extensão por zero)
                vizinhanca = ((vizinhanca - minimo)/(maximo - minimo))*255 # aplicando a expansão de histograma com foco na vizinhança
                pos = np.sum(vizinhanca * filtro) + offset #aplicando o filtro na posição (q,w)
                img_resultante[q,w] = np.absolute(pos) # valor absoluto seguido por expansão de histograma para [0, 255]
                img_resultante[q][w] = np.clip(img_resultante[q][w],0,255)

    imagem_resultante = cv2.imwrite(nome_resultado, img_resultante)

    return imagem_resultante

In [62]:
resultado = filter('Shapes.png','Gaussiano_5x5.txt','Shapes_Gaussiano_5x5.png')
print(resultado) # retorna True se salvou com sucesso

True


In [ ]:
resultado = filter('Shapes.png','Sobel_h.txt','Shapes_Sobel_h.png')
print(resultado) # retorna True se salvou com sucesso

True


In [63]:
resultado = filter('Shapes.png','Sobel_v.txt','Shapes_Sobel_v.png')
print(resultado) # retorna True se salvou com sucesso

True


In [78]:
resultado = filter('testpat.tif','Gaussiano_5x5.txt','testpat_Gaussiano_5x5.tif')
print(resultado) # retorna True se salvou com sucesso

True


In [79]:
resultado = filter('testpat.tif','Sobel_h.txt','testpat_Sobel_h.tif')
print(resultado) # retorna True se salvou com sucesso

True


In [ ]:
resultado = filter('testpat.tif','Sobel_v.txt','testpat_Sobel_v.tif')
print(resultado) # retorna True se salvou com sucesso

True


2. Filtro pontual a seguir 

![Filtro Pontual](Filtro_Pontual.png)

(a) aplicado em RGB

In [58]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

f = 'Sobel_h.txt'
i = 'testpat.tif'
with open(f, 'r') as f:  # abrindo o txt do filtro
    m = int(f.readline()) # linhas
    n = int(f.readline()) # colunas
    offset = int(f.readline())
    filtro = [[0] * n for _ in range(m)] # criando uma matriz para colocar o filtro
    linhas = f.readlines()

    for j, line in enumerate(linhas): # colocando o filtro na matriz criada
        f1 = (line.split())
        filtro[j] = f1

    for e in range(m): # transformando cada posição do filtro em ponto flutuante
        for r in range(n):
            filtro[e][r] = float(filtro[e][r])

img = cv2.imread(i) # lendo a imagem
img_m, img_n, _ = img.shape # terceira dimensão = bandas (R,G,B)

img_resultante = np.zeros_like(img) # gerando uma imagem resultante de mesmo tamanho da imagem de entrada

'''
A partir daqui já temos todas as informações necessárias para aplicarmos o filtro à imagem:
    - m
    - n
    - offset
    - filtro
    - imagem
    - altura da imagem (qtd de linhas)
    - largura da imagem (qtd de colunas)
    - imagem resultante (preenchida com zeros e pronta para receber os cálculos da aplicação do filtro)
        A imagem resultante tem o mesmo tamanho da imagem de entrada, pois utilizaremos extensão por zero
'''
# Separando os canais
R = img[:,:,0]
G = img[:,:,1]
B = img[:,:,2]

expansao = ((ponto_na_imagem - min(valor_no_canal))/(max(valor_no_canal) - min(valor_no_canal)))*255

for b in [R, G, B]: # Aplicando o filtro em cada canal
    padded_b = np.pad(b, ((m//2, m//2), (n//2, n//2)), mode='constant') # corrigindo o problema das dimensões
    for q in range(img_m): # aplicar o filtro em cada posição da imagem
        for w in range(img_n):
            vizinhanca = padded_b[q:q+m, w:w+n] # recortando a vizinhança para realizar a convolução do filtro (considerando a extensão por zero)
            pos = np.sum(vizinhanca * filtro) + offset #aplicando o filtro na posição (q,w)
            img_resultante[q,w] = np.absolute(pos) # valor absoluto seguido por expansão de histograma para [0, 255]
            img_resultante[q][w] = np.clip(img_resultante[q][w],0,255)


NameError: name 'ponto' is not defined

In [57]:
print(R)
# print(G)
# print(B)
# print(img)
# print(img_resultante[q,w,0])

[[149 150 150 ... 150 149 150]
 [150 149 149 ... 149 149 149]
 [150 150 149 ... 150 149 149]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


(b) aplicado à banda Y do YIQ, com posterior conversão a RGB